#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
echo "127.0.0.2 localhost" >> /etc/hosts

# Set facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
